### ISSUE TITLE
REST API interface for CRUD operations in eoAPI (Q2)

### ISSUE THREAD

**Issue by kalxas** [EOEPCA/resource-discovery#67]
Initial work for #20 

## Sub-tasks

- [x] https://github.com/developmentseed/eoapi-k8s/issues/33

**Comment by j08lue** [comment]
Transaction API implemented, see https://eoapi.develop.eoepca.org/stac/api.html#/Transaction%20Extension

![Image](https://github.com/user-attachments/assets/5a9d08c7-a97a-4aed-a781-52241b665e9b)
